spring:
  jpa:
    show-sql: false
    properties:
      hibernate:
        format_sql: false
  datasource:
    jndi-name: java:jboss/datasources/oraclevmcard
    
keycloak:
  config:
    clientesunimed:
      file: clientesRealm-keycloak.json


triagil:
  authentication:
    authorization-header: 'Bearer 93uw4bjoT-StYBWHf_RKF1w6DjwwOOoD5dd_9X3_aWU'
  service:
    score-url: 'https://api.dev.triagil.com.br/autorizai/v1/sync/score'

