spring:
  jpa:
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        hbm2ddl:
          auto: update
        connection:
          SetBigStringTryClob: true
        jdbc:
          batch_size: 0
    database-platform: org.hibernate.dialect.OracleDialect

  datasource:
    #url: jdbc:h2:mem:testdb;INIT=RUNSCRIPT FROM 'classpath:init.sql'
    #driverClassName: org.h2.Driver
    #username: sa
    #password: password
    url: jdbc:oracle:thin:@-:1521/unmtst.-.com.br
    driverClassName: oracle.jdbc.driver.OracleDriver
    username: -
    password: -*
    #jndi-name: java:jboss/datasources/-

keycloak:
  config:
    clientesunimed:
      file: stageRealm-keycloak.json

logging:
  level:
    org.springframework.web.client.RestTemplate: DEBUG

triagil:
  authentication:
    authorization-header: -
  service:
    score-url: -
