spring:
  jpa:
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        hbm2ddl:
          auto: update
  datasource:
    jndi-name: -

keycloak:
  config:
    clientesunimed:
      file: -


triagil:
  authentication:
    authorization-header: -
  service:
    score-url: -
