spring:
  jpa:
    show-sql: false
    properties:
      hibernate:
        format_sql: false
  datasource:
    jndi-name: -
    
keycloak:
  config:
    clientesunimed:
      file: -


triagil:
  authentication:
    authorization-header: -
  service:
    score-url: -

